Discussion[1]="Sudost funkce";
Discussion[2]="Lichost funkce";
QuizSpecifications[1]=[];
QuizSpecifications[1].type="single";
QuizSpecifications[1][0]=false;
QuizSpecifications[1][1]=false;
QuizSpecifications[1][2]=false;
QuizSpecifications[1][3]=true;
QuizSpecifications[2]=[];
QuizSpecifications[2].type="input";
QuizSpecifications[2].value="-8";
QuizSpecifications[2].comparison="integer";
QuizSpecifications[3]=[];
QuizSpecifications[3].type="multiple";
QuizSpecifications[3][0]=false;
QuizSpecifications[3][1]=true;
QuizSpecifications[3][2]=true;
QuizSpecifications[3][3]=false;
QuizSpecifications[4]=[];
QuizSpecifications[4].type="single";
QuizSpecifications[4][0]=false;
QuizSpecifications[4][1]=true;
QuizSpecifications[4][2]=false;
QuizSpecifications[4][3]=false;
initSession();
gotoQuestion(-1);